### ISSUE TITLE
game1.rb Texplay dependency won't install (for some people)

### ISSUE THREAD

**Issue by russplaysguitar** [ChicoTeam/chingu#3]
Building native extensions.  This could take a while...
ERROR:  Error installing texplay:
    ERROR: Failed to build gem native extension.

```
    /home/russ/.rvm/rubies/ruby-1.8.7-p352/bin/ruby extconf.rb
```

checking for main() in -lglut... no
**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/home/russ/.rvm/rubies/ruby-1.8.7-p352/bin/ruby
    --with-glutlib
    --without-glutlib

Gem files will remain installed in /home/russ/.rvm/gems/ruby-1.8.7-p352@chingu/gems/texplay-0.3.5 for inspection.
Results logged to /home/russ/.rvm/gems/ruby-1.8.7-p352@chingu/gems/texplay-0.3.5/ext/texplay/gem_make.out

**Comment by flipcoder** [comment]
You need the glut library.
For ubuntu:
sudo apt-get install libglut3-dev

**Comment by russplaysguitar** [comment]
That totally fixed it! Thanks Grady!
