### ISSUE TITLE
game1: Cannot hold left+up+spacebar

### ISSUE THREAD

**Issue by russplaysguitar** [ChicoTeam/chingu#5]
You can use any other arrow and spacebar combo, but not this one.

**Comment by jschall** [comment]
Likely specific to your hardware. Just keyboard ghosting/keyboard masking.
The only solution is change the keyboard or change the key binds.

**Comment by jschall** [comment]
I hate that. I always comment and close instead of commenting.

**Comment by russplaysguitar** [comment]
haha. Do you have a problem with this? 

FYI I just found a file that might be related: /chingu/lib/chingu/helpers/input_client.rb

**Comment by russplaysguitar** [comment]
this is a problem in all the examples i try, so i think it is a framework issue

**Comment by russplaysguitar** [comment]
i think you're right, i just tested my keyboard on a non-chingu game and had the problem, so it was just me!
